import type { Offer, Review } from "@/lib/cmsTypes";

export const defaultOffers: Offer[] = [
  {
    id: "offer-1",
    title: "The Ultimate Combo",
    subtitle: "Curry + Naan + Lassi",
    description:
      "Get our signature Classic Butter Chicken with freshly baked tandoori garlic naan and a spiced mango lassi. The perfect meal deal.",
    originalPrice: "$26.97",
    salePrice: "$18.99",
    savings: "Save $7.98",
    badge: "Best Value",
    badgeColor: "bg-brand-orange",
    image:
      "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800&h=600&fit=crop&q=80",
    icon: "gift",
    timeLeft: "Limited Time",
  },
  {
    id: "offer-2",
    title: "Family Feast",
    subtitle: "4 Curries + 4 Naans + 4 Sides",
    description:
      "Feed the whole crew! Four curries of your choice, four garlic naans, a samosa platter, and four drinks. Perfect for family nights.",
    originalPrice: "$79.96",
    salePrice: "$54.99",
    savings: "Save $24.97",
    badge: "Family Deal",
    badgeColor: "bg-yellow-500",
    image:
      "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&h=600&fit=crop&q=80",
    icon: "zap",
    timeLeft: "Weekends Only",
  },
  {
    id: "offer-3",
    title: "Tandoori Date Night",
    subtitle: "Biryani + Tikka + Dessert",
    description:
      "Share an aromatic chicken biryani, a platter of smoky chicken tikka, and our delicious sweet rasmalai. Perfect for two.",
    originalPrice: "$54.97",
    salePrice: "$39.99",
    savings: "Save $14.98",
    badge: "Romantic",
    badgeColor: "bg-red-500",
    image:
      "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800&h=600&fit=crop&q=80",
    icon: "tag",
    timeLeft: "Fri & Sat Only",
  },
];

export const defaultReviews: Review[] = [
  {
    id: "review-1",
    name: "Marcus Johnson",
    handle: "@marcuseats",
    avatar: "MJ",
    avatarBg: "from-purple-500 to-blue-600",
    rating: 5,
    date: "2 weeks ago",
    text: "Honestly the best Indian food I've had in years. The Classic Butter Chicken is something else — that spice blend, that creamy texture, that charcoal tandoor hint. Ordered through DoorDash and it arrived piping hot. Will absolutely be back.",
    dish: "Classic Butter Chicken",
    image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&h=400&fit=crop",
    verified: true,
  },
  {
    id: "review-2",
    name: "Priya Sharma",
    handle: "@priyafoodie",
    avatar: "PS",
    avatarBg: "from-pink-500 to-rose-600",
    rating: 5,
    date: "1 month ago",
    text: "The garlic naan is next level. I've had flatbreads all over the world and this tandoori-baked naan competes with the best. Beautifully crafted, fresh flavors. The DoorDash delivery was super fast too.",
    dish: "Tandoori Garlic Naan",
    verified: true,
  },
  {
    id: "review-3",
    name: "Derek Thompson",
    handle: "@derekthompsonnyc",
    avatar: "DT",
    avatarBg: "from-orange-500 to-red-600",
    rating: 5,
    date: "3 weeks ago",
    text: "Tried the Family Feast combo for game night and everyone was blown away. Four different curries, all customized perfectly, and every single one was delicious. The value for the quality is unreal.",
    dish: "Family Feast Combo",
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&h=400&fit=crop",
    verified: true,
  },
  {
    id: "review-4",
    name: "Sophie Chen",
    handle: "@sophieeatsgood",
    avatar: "SC",
    avatarBg: "from-teal-500 to-emerald-600",
    rating: 5,
    date: "5 days ago",
    text: "The Paneer Tikka Masala converted my carnivore boyfriend! That grilled cottage cheese with the spiced gravy is just perfection. Finally an authentic vegetarian option that doesn't compromise on taste.",
    dish: "Paneer Tikka Masala",
    verified: true,
  },
  {
    id: "review-5",
    name: "James Rivera",
    handle: "@jamesreviews",
    avatar: "JR",
    avatarBg: "from-amber-500 to-yellow-600",
    rating: 5,
    date: "1 week ago",
    text: "The Rasmalai dessert is insane. Soft, sweet milk discs, that perfect cardamom flavor. And the Spiced Mango Lassi? I'm addicted. Curry Express gets everything right.",
    dish: "Sweet Rasmalai + Mango Lassi",
    verified: true,
  },
];
