import type { Offer, Review } from "@/lib/cmsTypes";

export const defaultOffers: Offer[] = [
  {
    id: "offer-1",
    title: "The Ultimate Combo",
    subtitle: "Burger + Fries + Drink",
    description:
      "Get our signature Smokehouse Classic with crispy smoked fries and a craft lemonade. The perfect meal deal.",
    originalPrice: "$26.97",
    salePrice: "$18.99",
    savings: "Save $7.98",
    badge: "Best Value",
    badgeColor: "bg-brand-orange",
    image:
      "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&h=600&fit=crop&q=80",
    icon: "gift",
    timeLeft: "Limited Time",
  },
  {
    id: "offer-2",
    title: "Family Feast",
    subtitle: "4 Burgers + 4 Sides",
    description:
      "Feed the whole crew! Four burgers, four sides of your choice, and four drinks. Perfect for family nights.",
    originalPrice: "$79.96",
    salePrice: "$54.99",
    savings: "Save $24.97",
    badge: "Family Deal",
    badgeColor: "bg-yellow-500",
    image:
      "https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=800&h=600&fit=crop&q=80",
    icon: "zap",
    timeLeft: "Weekends Only",
  },
  {
    id: "offer-3",
    title: "Date Night Special",
    subtitle: "Pizza + Wine + Dessert",
    description:
      "Share a wood-fired pizza, a bottle of house red, and our famous lava brownie. Perfect for two.",
    originalPrice: "$54.97",
    salePrice: "$39.99",
    savings: "Save $14.98",
    badge: "Romantic",
    badgeColor: "bg-red-500",
    image:
      "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&h=600&fit=crop&q=80",
    icon: "tag",
    timeLeft: "Fri & Sat Only",
  },
];

export const defaultReviews: Review[] = [
  {
    id: "review-1",
    name: "Marcus Johnson",
    handle: "@marcuseats",
    avatar: "MJ",
    avatarBg: "from-purple-500 to-blue-600",
    rating: 5,
    date: "2 weeks ago",
    text: "Honestly the best burger I've had in years. The Smokehouse Classic is something else — that char, that sauce, that bun. Ordered through DoorDash and it arrived piping hot. Will absolutely be back.",
    dish: "Smokehouse Classic",
    verified: true,
  },
  {
    id: "review-2",
    name: "Priya Sharma",
    handle: "@priyafoodie",
    avatar: "PS",
    avatarBg: "from-pink-500 to-rose-600",
    rating: 5,
    date: "1 month ago",
    text: "The Truffle Margherita pizza is next level. I've had pizza all over the world and this one competes with the best. Beautifully crafted, fresh flavors. The DoorDash delivery was super fast too.",
    dish: "Truffle Margherita",
    verified: true,
  },
  {
    id: "review-3",
    name: "Derek Thompson",
    handle: "@derekthompsonnyc",
    avatar: "DT",
    avatarBg: "from-orange-500 to-red-600",
    rating: 5,
    date: "3 weeks ago",
    text: "Tried the Family Feast combo for game night and everyone was blown away. Four burgers, all customized differently, and every single one was perfect. The value for the quality is unreal.",
    dish: "Family Feast Combo",
    verified: true,
  },
  {
    id: "review-4",
    name: "Sophie Chen",
    handle: "@sophieeatsgood",
    avatar: "SC",
    avatarBg: "from-teal-500 to-emerald-600",
    rating: 5,
    date: "5 days ago",
    text: "The Garden Blaze veggie burger converted my carnivore boyfriend! That plant-based patty with the avocado cream is just perfection. Finally a veggie option that doesn't compromise on taste.",
    dish: "Garden Blaze Burger",
    verified: true,
  },
  {
    id: "review-5",
    name: "James Rivera",
    handle: "@jamesreviews",
    avatar: "JR",
    avatarBg: "from-amber-500 to-yellow-600",
    rating: 5,
    date: "1 week ago",
    text: "The Lava Brownie dessert is insane. Warm, gooey, that perfect vanilla ice cream melting into it. And the Smoky Iced Coffee? I'm addicted. This place gets everything right.",
    dish: "Lava Brownie + Iced Coffee",
    verified: true,
  },
];
